dubbo:
  scan.base-packages: ${hp.soa.web.component-scan.base-package}
  registry:
    file: "/data/hp-soa/.cache/dubbo-registry_${hp.soa.web.app.name}.properties"
  application:
    #qos-enable: false
    name: ${hp.soa.web.app.name}
    version: ${hp.soa.web.app.version}
    owner: ${hp.soa.web.app.owner:}
    organization: ${hp.soa.web.app.organization:}