global-transaction-management:
  enabled: true
  #timeout: 3000
  #isolation: ISOLATION_READ_COMMITTED
  #propagation: PROPAGATION_REQUIRED
  #rollback-for: java.lang.Exception
  #read-only-timeout: 3000
  #read-only-isolation: ISOLATION_READ_COMMITTED
  #read-only-propagation: PROPAGATION_REQUIRED
  #pointcut-expression: "execution(* ${hp.soa.web.component-scan.base-package}..service..*.*(..))"

hp.soa.web.app.read-only: false